### ISSUE TITLE
Create folders if they don't exist

### ISSUE THREAD

**Issue by rvignesh89** [PureKrome/YUICompressor.NET#13]
Hi @PureKrome,

I just gave this msbuild task a try and found it really convenient! I haven't evaluated the correctness of the compression yet as it was only a trial. But I noticed one feature which was desperately lacking was the ability for the compressor to create missing folders by default. Because of this I'm having to create the folders before hand. Since my Js files exist in nested folders I don't have a choice but to recursively copy the entire structure before I transform. Here is what I'm doing.

``` xml
<Target Name="BuildJsAndCss" BeforeTargets="WebFileSystemPublish">
    <MakeDir Directories="$(OutputPath)obj\Debug\Package\PackageTmp\js"></MakeDir>
    <MakeDir Directories="$(OutputPath)obj\Debug\Package\PackageTmp\css"></MakeDir>
    <Copy
        SourceFiles="@(_JsItemsToCopy)"
        DestinationFiles="@(_JsItemsToCopy->'$(OutputPath)obj\Debug\Package\PackageTmp\js\%(RecursiveDir)%(Filename)%(Extension)')"
    />
    <Copy
        SourceFiles="@(_CssItemsToCopy)"
        DestinationFiles="@(_CssItemsToCopy->'$(OutputPath)obj\Debug\Package\PackageTmp\css\%(RecursiveDir)%(Filename)%(Extension)')"
    />
    <JavascriptCompressorTask
      SourceFiles="%(JavascriptFiles.Identity)"
      OutputFile="$(OutputPath)obj\Debug\Package\PackageTmp\%(JavascriptFiles.Identity)"></JavascriptCompressorTask>
    <CssCompressorTask
      SourceFiles="%(CssFiles.Identity)"
      OutputFile="$(OutputPath)obj\Debug\Package\PackageTmp\%(CssFiles.Identity)"></CssCompressorTask>
  </Target>
```

This feels cumbersome and unnecessary if the compressor is able to create the folder structure for me. Let me know if you think likewise. I could even give you pull request if you think this makes sense.

**Comment by PureKrome** [comment]
Heya mate! 

I _sorta_ get your drift. PR away so I can see what you're thinking, mate.

**Comment by freeranger** [comment]
@rvignesh89 - your PR for this needs some attention if you want it merged into the codebase
thanks.

**Comment by freeranger** [comment]
PR merged
