### ISSUE TITLE
Inconsistent EOL-Style

### ISSUE THREAD

**Issue by kenmark** [PureKrome/YUICompressor.NET#15]
When I commit a minified css file to Subversion is refuses to do it because of "Inconsistent EOL-Style". Is it something that could be solved?

**Comment by freeranger** [comment]
Hi - why are you committing the minified files to svn in the first place?
That's not the normal practice in my experience - you commit your source files to source control, no need for the build output to go there also.

Also, can you provide any more info about this - where does it think the line endings are inconsistent?
Is it a minified file created from one single source or multiple sources?
What options are you using?
It would be useful if you could provide a minimal project that reproduces this behaviour

**Comment by freeranger** [comment]
Closing due to lack of response from the reporter
