### ISSUE TITLE
Signed package

### ISSUE THREAD

**Issue by tomap** [PureKrome/YUICompressor.NET#16]
Hi,

Following up on #1 , I needed a signed package so I pushed one to nuget:
https://www.nuget.org/packages/YUICompressor.NET.Signed/
from this fork:
https://github.com/tomap/YUICompressor.NET

I also switched to .Net 4.5 :)

Regards,

Thomas

**Comment by PureKrome** [comment]
Thanks kindly Thomas for helping the community :+1:
