### ISSUE TITLE
VueJS missing : after property id

### ISSUE THREAD

**Issue by jrenton** [PureKrome/YUICompressor.NET#17]
Hi -

We are having troubles compressing [VueJS](http://vuejs.org/js/vue.js) using this package, although it works just fine using the original java version. Error message:

```
Failed to read/parse data in file [\scripts\libraries\vue.js]
missing : after property id 
```

Also, it would help if the error message included the line number in the JS file that is being compressed so that we can debug it more easily.

**Comment by freeranger** [comment]
Can you put together a minimal example project demonstrating the problem?

**Comment by freeranger** [comment]
Closing due to lack of response from reporter
