### ISSUE TITLE
Support for .NET Core?

### ISSUE THREAD

**Issue by UweKeim** [PureKrome/YUICompressor.NET#18]
Do you any plans to support your library running on [.NET Core](https://www.microsoft.com/net/core) in the near future?

**Comment by PureKrome** [comment]
Nope.

Why -> I feel like this library should be put into `Maintenance Mode` as there are heaps better options IMO now to do minification/bundling.

**Comment by UweKeim** [comment]
Thanks. Can you clarify on these better options from your point-of-view?

I'm using your awesome library in a WinForms desktop application ([a german CMS](https://www.zeta-producer.com/de/index.html)) and never found an alternative way to compress JavaScript and CSS other than your library.

So I'm _very_ keen on knowing what you see as the alternatives.

**Comment by PureKrome** [comment]
Oh wow. I never thought that this library would be used in a _desktop_ application. Um .. er ... I don't really have an honest answer, actually :blush: 

I was thinking this library would only be used with ASP.NET websites .. which most people are using grunt/gulp/webpack, etc to do all their minification and bundling these days.

**Comment by freeranger** [comment]
What an interesting application for it - just goes to show how you should never make assumptions about how your library will be used :)
@UweKeim Are you using it as a library or using the msbuild tasks?
Also have you considered having a crack at porting to .NET Core yourself?

Or, as @PureKrome says, you could look at gulp or web pack as the cool kid on the block now to do your minification....

**Comment by UweKeim** [comment]
@freeranger As a library.

The user of can activate a checkbox and let all his CSS and JavaScript files getting compressed before uploading to their FTP server.

Probably I can include Nodejs into my application and use some library out there to compress.

**Comment by PureKrome** [comment]
>What an interesting application for it - just goes to show how you should never make assumptions about how your library will be used :)

:point_up: this!

**Comment by freeranger** [comment]
Hmm... I just ran the portability analyser: https://visualstudiogallery.msdn.microsoft.com/1177943e-cfb7-4822-a8a6-e56c7905292b

and according to it, our codebase is highly compatible, so it would be fairly trivial to port:

![image](https://cloud.githubusercontent.com/assets/1401069/17626117/ceb26d52-60a3-11e6-8ea3-4234313a82b5.png)
