### ISSUE TITLE
Windows Update, dependencies removed.

### ISSUE THREAD

**Issue by solidcloudio** [PureKrome/YUICompressor.NET#19]
These custom build tasks no longer seems to work as it's targeting 2.0 .net assemblies. After Windows Update ran on my build machine I get: 
error MSB4062: The "CssCompressorTask" task could not be loaded from the assembly packages\YUICompressor.NET.MSBuild.2.7.0.0\lib\NET20\Yahoo.Yui.Compressor.Build.MsBuild.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask

This assembly is no longer in my GAC

**Comment by solidcloudio** [comment]
I updated this to 2.8.0.0 and upgraded the project to use .NET 4.5.2 and MSBuildUtilities 4.0   This is forked under: https://github.com/solidcloudio/YUICompressor.NET

**Comment by PureKrome** [comment]
Ok. so, is it possible that you don't have .NET 2.0 installed? I know i don't (and haven't) for well... ages.

Is it possible to set the project to be the lowest .net 4 type (to make it as widely available as possible) ?

**Comment by solidcloudio** [comment]
Most recent Windows update must have removed .net 2.0.  Was working fine until yesterday.

**Comment by freeranger** [comment]
I don't believe this is the case as I can't find any reference to microsoft removing the .NET framework and nobody else has reported a problem...
