### ISSUE TITLE
Iesi.Collections has a conflict with NHibernate

### ISSUE THREAD

**Issue by katlimruiz** [PureKrome/YUICompressor.NET#6]
Iesi.Collections has a conflict with NHibernate which uses version 4.0 and this project uses 2.0.

Iesi.Collections should get updated asap! :+1:

**Comment by freeranger** [comment]
What’s the use case for this?
YUICompressor is typically used at compile time, whereas nhibernate would be used at runtime.

Also 4.0 is a .NET 4 library but we target .NET 2 and above…

**Comment by katlimruiz** [comment]
Indeed you are right, it is used at build time, however I think the issue is that I got the YUICompressor MSBuildTask package but this has a dependency on YUICompressor package, so nuget brings both. 
The funny thing is that the folder content of MsBuildTask package does not have the Iesi.Collections but the other does (I would had assume both would have it as a requirement).

So maybe there is a way to break this link?

**Comment by freeranger** [comment]
But you can have nugget dependencies on different versions of the same package so it shouldn’t be an issue.
http://stackoverflow.com/questions/9942041/nuget-managing-and-removing-multi-version-packages-in-single-solution <http://stackoverflow.com/questions/9942041/nuget-managing-and-removing-multi-version-packages-in-single-solution>

**Comment by freeranger** [comment]
Closing due to no response from the raiser, and it should not be a problem as previously posted
