### ISSUE TITLE
Add warning for naked commas

### ISSUE THREAD

**Issue by rumincayman** [PureKrome/YUICompressor.NET#9]
We use YUICompressor.NET in our build chain, and we like the "compile"-time checks that are performed to tell us about potential issues in our javascript codebase. We found an issue with IE7 clients around an edge-case in Javascript syntax. If there were any array or object declarations with a comma and no other token between the closing brace or bracket, an exception would be thrown. See below example. This seems to be acceptable in other browsers.

```javascript
var anObject = {a:1, b:'2',}; // the last comma causes an exception in IE7 and earlier
var anArray = [1,2,3,]; //  the last comma causes an exception in IE7 and earlier
```
We decided to disallow this in our codebase to be safe, and added a check to YUICompressor.NET to find and warn on these situations.

I have added a new option *DisallowNakedComma* to warn on the above situation, which is defaulted to NOT warn for backwards compatibility.

**Comment by freeranger** [comment]
Hi,

I'm not sure it is appropriate in yuicompressor - following the principle of single responsibility, the compressor is responsible for compressing JavaScript, not enforcing good practice.
Have you thought of using something like jslint?
If we were going to implement this, naked comma is a bad name - trailing comma at least tells you want it is - I have no idea what a "naked" comma is.

Also, you should have one test per test case with a single assert in each, not four test cases in one test and multiple asserts.

@PureKrome is the owner of the repo so up to him, but I would suggest using jslint for your code quality and keep yuicompressor for compressing.

**Comment by PureKrome** [comment]
@freeranger YUIC also handles minification ... but I'm not sure if this comes under that umbrella?

unless it's _breaking_ the minification and combining...

**Comment by freeranger** [comment]
"Also" handles minification? That's the main purpose surely! 😅
